#!/bin/bash

# Usage: ./trade [coin] [flags]
# Example: ./trade btc --shares=50

COIN=$1
shift # Remove the first argument (coin) so the rest can be passed directly

if [ -z "$COIN" ]; then
  echo "Usage: ./trade <coin> [options]"
  echo "Coins: btc, eth, sol, xrp"
  exit 1
fi



if [ "$COIN" == "-redeem" ]; then
  npx tsx src/main.ts -redeem
  exit 0
fi

if [ "$COIN" == "-info" ]; then
  npx tsx src/main.ts -info
  exit 0
fi

if [ "$COIN" == "-dashboard" ]; then
  npx tsx src/main.ts -dashboard
  exit 0
fi

# Run the bot with the coin flag and any other passed arguments
npx tsx src/main.ts --$COIN "$@"
